### ISSUE TITLE
what is the secrets/demo-cicd.yml?

### ISSUE THREAD

**Issue by dsl2022** [Osones/demo-cicd#1]
Hi, I have been trying to replicate your tutorial locally and I couldn't figure out what would the secrets/demo-cicd.yml be. It seems it is the credential I will to sign in in the docker image? would you mind giving me some clue thanks.

**Comment by rguichard** [comment]
It will be the values you want to load into your Concourse pipeline. And indeed, the file will contain password, credentials, access key etc.

For example for this resource declaration :

```
resources:
  - name: docker-blog
    type: docker-image
    source:
      repository: particule/testimage
      username: particule
      password: {{dockerhub-particule-password}}
```

You'll need to load a var file like this : 
```
---
dockerhub-particule-password: "myawesomepassword"
```

Is it clearer now ? You can contact me directly at romain@particule.io if you want more information and/or follow us @particuleio
